# Statistics template - exact output labels for the canonical JSON contract.
STATISTICS_TEMPLATE = [
    {"stt": "1", "noi_dung": "I. TÌNH HÌNH CHÁY, NỔ, SỰ CỐ TAI NẠN"},
    {"stt": "2", "noi_dung": "1. Tổng số vụ cháy"},
    {"stt": "3", "noi_dung": "Số người chết"},
    {"stt": "4", "noi_dung": "Số người bị thương"},
    {"stt": "5", "noi_dung": "Số người cứu được"},
    {"stt": "6", "noi_dung": "Tài sản thiệt hại (ước tính triệu đồng)"},
    {"stt": "7", "noi_dung": "Tài sản cứu được (ước tính triệu đồng)"},
    {"stt": "8", "noi_dung": "2. Tổng số vụ nổ"},
    {"stt": "9", "noi_dung": "Số người chết"},
    {"stt": "10", "noi_dung": "Số người bị thương"},
    {"stt": "11", "noi_dung": "Số người cứu được"},
    {"stt": "12", "noi_dung": "Tài sản thiệt hại (ước tính triệu đồng)"},
    {"stt": "13", "noi_dung": "Tài sản cứu được (ước tính triệu đồng)"},
    {"stt": "14", "noi_dung": "3. Tổng số vụ tai nạn, sự cố"},
    {"stt": "15", "noi_dung": "Số người cứu được (=STT 16+STT 17)"},
    {"stt": "16", "noi_dung": "Trong đó, số người trực tiếp cứu được"},
    {"stt": "17", "noi_dung": "Trong đó, số người tổ chức hướng dẫn tự thoát nạn"},
    {"stt": "18", "noi_dung": "Số thi thể nạn nhân tìm được"},
    {"stt": "19", "noi_dung": "Số tài sản cứu được (ước tính triệu đồng)"},
    {"stt": "20", "noi_dung": "II. KẾT QUẢ CÔNG TÁC PCCC VÀ CNCH"},
    {"stt": "21", "noi_dung": "1. Tuyên truyền về PCCC và CNCH"},
    {"stt": "22", "noi_dung": "1.1. Tuyên truyền qua các phương tiện thông tin truyền thông và nền tảng trực tuyến MXH (zalo, facebook, youtube, Website)"},
    {"stt": "23", "noi_dung": "Số tin, bài đã đăng phát"},
    {"stt": "24", "noi_dung": "Số hình ảnh được đăng tải"},
    {"stt": "26", "noi_dung": "1.2. Tuyên truyền trực tiếp tại cơ sở, doanh nghiệp, các khu dân cư"},
    {"stt": "27", "noi_dung": "Số cuộc"},
    {"stt": "28", "noi_dung": "Số người tham dự"},
    {"stt": "29", "noi_dung": "Số khuyến cáo, tờ rơi đã phát hành"},
    {"stt": "30", "noi_dung": "2. Hướng dẫn, kiểm tra về PCCC và CNCH"},
    {"stt": "31", "noi_dung": "Số cơ sở được kiểm tra an toàn PCCC (=STT 32+STT 33)"},
    {"stt": "32", "noi_dung": "Kiểm tra định kỳ"},
    {"stt": "33", "noi_dung": "Kiểm tra đột xuất theo chuyên đề"},
    {"stt": "34", "noi_dung": "Số vi phạm được phát hiện"},
    {"stt": "35", "noi_dung": "Tổng số cơ sở bị xử phạt VPHC về PCCC (=STT 36+...+STT 39)"},
    {"stt": "36", "noi_dung": "Trong đó, phạt cảnh cáo"},
    {"stt": "37", "noi_dung": "Trong đó, tạm đình chỉ hoạt động"},
    {"stt": "38", "noi_dung": "Trong đó, đình chỉ hoạt động"},
    {"stt": "39", "noi_dung": "Trong đó, phạt tiền"},
    {"stt": "40", "noi_dung": "Số tiền phạt thu được (triệu đồng)"},
    {"stt": "41", "noi_dung": "3. Xây dựng, thực tập phương án chữa cháy, CNCH"},
    {"stt": "42", "noi_dung": "3.1. Phương án chữa cháy, cứu nạn, cứu hộ của cơ sở theo Mẫu số PC 06 kèm theo Nghị định số 105/2025/NĐ-CP"},
    {"stt": "43", "noi_dung": "Số phương án được xây dựng và phê duyệt"},
    {"stt": "44", "noi_dung": "Số phương án được thực tập"},
    {"stt": "45", "noi_dung": "3.2. Phương án chữa cháy, cứu nạn, cứu hộ của phương tiện giao thông được xây dựng và phê duyệt theo Mẫu số PC 07 kèm theo Nghị định số 105/2025/NĐ-CP"},
    {"stt": "46", "noi_dung": "Số phương án được xây dựng và phê duyệt"},
    {"stt": "47", "noi_dung": "Số phương án được thực tập"},
    {"stt": "48", "noi_dung": "3.3. Phương án chữa cháy, cứu nạn, cứu hộ của cơ quan Công an thực hiện theo Mẫu số PC 08 kèm theo Nghị định số 105/2025/NĐ-CP"},
    {"stt": "49", "noi_dung": "Số phương án được xây dựng và phê duyệt"},
    {"stt": "50", "noi_dung": "Số phương án được thực tập"},
    {"stt": "51", "noi_dung": "3.4. Phương án cứu nạn, cứu hộ của cơ quan Công an thực hiện theo Mẫu số PC 09 kèm theo Nghị định số 105/2025/NĐ-CP"},
    {"stt": "52", "noi_dung": "Số phương án được xây dựng và phê duyệt"},
    {"stt": "53", "noi_dung": "Số phương án được thực tập"},
    {"stt": "54", "noi_dung": "4. Công tác huấn luyện nghiệp vụ chữa cháy và CNCH thường xuyên"},
    {"stt": "55", "noi_dung": "Tổng số CBCS tham gia huấn luyện (=STT 56+...+STT 61)"},
    {"stt": "56", "noi_dung": "Chỉ huy phòng"},
    {"stt": "57", "noi_dung": "Chỉ huy Đội"},
    {"stt": "58", "noi_dung": "Cán bộ tiểu đội"},
    {"stt": "59", "noi_dung": "Chiến sỹ CC và CNCH"},
    {"stt": "60", "noi_dung": "Lái xe CC và CNCH"},
    {"stt": "61", "noi_dung": "Lái tàu CC và CNCH"},
]

DEFAULT_KET_QUA = 0
